### ISSUE TITLE
Automatically detect user location and display the weather of their city and cities close by. - (Hacktober Fest )

### ISSUE THREAD

**Issue by shuMan3114** [theravi04/Frontend_Projects#12]
We  use a grid system which changes based on screen size ( maybe a 1*3 on phones 2*3 on tablets and 3*3 on laptops). 
This issue can be divided into three main parts:
- Getting user location 
- Getting the weather of major cities close by ( we could use on the three methods mentioned below)
- Updating the website ( would suggest using ejs for this) 

### **Finding User Location:** 
Use the IPstack API To get Location using User's IP address. 

### **Adding "Major Cities":**
We could do one of the three methods:

1.  **Using another API to fetch major cities close to the user.**
- API : GeoDB cities API.
- Has a lot of params to filter cities, like min , max population , radius , country_region, etc.
- We essentially fetch the coordinates from each city and pass it to the weather API, the only constrain over here would be the time taken to do so. 
- The output format will be common for both of the solutions, and is described below. 
2.  **Display the weather of major cities close to the user from a fixed list set by us.**
- For this we could use a dictionary which contains the name of the city (in accordance with openWeather's syntax for names) as the key , and a list containing [latitude and longitude] as the value. 
- We could iterate this dictionary and compare it with the current user location and retrieve the weather of the 4 closest cities. 
3.  **Display the weather of all major cities from a list like @kaushalkumar99 suggested, accept we use grid. (I was not sure if @kaushalkumar99  was referring to a grid system when he mentioned placement)** 
- [Issue Link](https://github.com/theravi04/Frontend_Projects/issues/6)
- This is relatively simpler as we iterate through a pre-determined list and fetch the weather of the cities.

### **Updating the website and possible style**
This will be a Major step up from the current website; but i propose switching to ejs templates instead of html files.
For the styling part refer to the image attached. 
I have partially modified a previous website which I made; The main intention of this mockUp is to show what I want the website to look like. 
Do focus on the card which says Name of The city,

![Screenshot 2023-10-10 220347](https://github.com/theravi04/Frontend_Projects/assets/40137599/7d0e6dd5-91ca-46d4-880b-8b699a5dc165)

### **Misc**
- I do have experience with geoLocation APIs, however, I am a little rusty in webdev right now, because I haven't done it in a year. 
- I am open to suggestions and I think the first method listed in " Adding major cities " should be our end goal for this website. 
- I can start from the second method and work up to the first method. 
- **TO minimize merge conflicts I am happy to purely work on getting current user location and fetching the weather.**
- I can do multiple pull requests to edit the CSS and other aspects of my issue.

Apologies for such a long comment.
~ The End ~

**Comment by theravi04** [comment]
@shuMan3114 assigned you

**Comment by SamaD-01** [comment]
i can take this issue
