### ISSUE TITLE
Instead of folders share files

### ISSUE THREAD

**Issue by ashishk1331** [theravi04/Frontend_Projects#14]
## Context
For now, we need to share entire folders of static data.

## Possible Solution
Instead of sharing entire folders, the contributors can share files in markdown format to display the project's information. eg.

```markdown
---
title: Project Name
project_url: link to the real demo of the project
author: name of the author
github_username: GitHub username
github_repository_link: link to the GitHub repository
---
```
Now, the new contributors can duplicate the above code from contributing.md or we can provide a sample.md file to just replace placeholder data with your actual data.
This approach will include:
1. creating a sample template
2. adding the rule to the contributing.md

Also, it approves of clean code.

## Assignment Request
I would love to make all the necessary changes mentioned above. Please assign me to this issue.

**Comment by theravi04** [comment]
@ashishk1331 This type of PR will excluede this repo from HacktoberFest as you are not allowed to store any info
about contributors
