### ISSUE TITLE
Add Random Quote Generator Website 

### ISSUE THREAD

**Issue by PrathameshTheurkar** [theravi04/Frontend_Projects#16]

**Comment by PrathameshTheurkar** [comment]
I would like to add the Random Quote Generator website using HTML , CSS and JS .
Can you plz assign me this issue under hacktoberfest

**Comment by PrathameshTheurkar** [comment]
I have made a PR #17  plz review the PR and merge it under hacktoberfest

**Comment by theravi04** [comment]
@PrathameshTheurkar the Quotes are not getting generated
![image](https://github.com/theravi04/Frontend_Projects/assets/96580159/c42c1fb3-e0c8-4a38-aa0b-46db0e6c9396)

**Comment by theravi04** [comment]
@PrathameshTheurkar correct your code & request a new PR

**Comment by PrathameshTheurkar** [comment]
> @PrathameshTheurkar correct your code & request a new PR

ok

**Comment by PrathameshTheurkar** [comment]
> @PrathameshTheurkar the Quotes are not getting generated ![image](https://user-images.githubusercontent.com/96580159/274493912-c42c1fb3-e0c8-4a38-aa0b-46db0e6c9396.png)

ya let me check

**Comment by PrathameshTheurkar** [comment]
Now can you check my PR #29

**Comment by PrathameshTheurkar** [comment]
Now the Quotes are getting generated.
