### ISSUE TITLE
Drop Down Suggestion of  Cities

### ISSUE THREAD

**Issue by TandinDev** [theravi04/Frontend_Projects#2]
I would love to add a drop down suggestion when user click or select the field. Please assign this issue to me.

**Comment by theravi04** [comment]
@TandinDev how will you implement this feature.

**Comment by Reechychukz** [comment]
Hey, by dropdown suggestion of cities, you mean to suggest based on selected country?

**Comment by TandinDev** [comment]
@theravi04 hey I was ale to achieve it. 
![ezgif com-video-to-gif (5)](https://github.com/theravi04/Frontend_Projects/assets/62091702/8a1f9648-b189-476d-9354-7c14ffc35f06)

I use this website for free location: https://www.geonames.org/
I added on readme file how to do it. Can you assign this to me and also, can you assign the hacktober label as well.

**Comment by theravi04** [comment]
@TandinDev Assigned you,
Clone the repo again to avoid any conflict.

**Comment by TandinDev** [comment]
@theravi04 It is done. Can you review this PR: https://github.com/theravi04/Frontend_Projects/pull/38
