### ISSUE TITLE
[Bug]: Date of Birth Input Length Validation

### ISSUE THREAD

**Issue by vedika-gupta** [theravi04/Frontend_Projects#20]
<strong>Issue Description:</strong> The "Date of Birth" input fields in the Payment form should be limited to accepting exactly 2 characters for "DD," 2 characters for "MM," and 4 characters for "YYYY" to enforce the desired date format (e.g., "DD-MM-YYYY" or "MM/DD/YYYY").

![Screenshot 2023-10-12 144809](https://github.com/theravi04/Frontend_Projects/assets/107416261/2a375bd5-bf4a-4f9a-b7d4-12b3038d60cc)

<strong>Expected behaviour:</strong> 

<ul>
<li>The "DD" input field should accept exactly 2 numeric characters.</li>
<li>The "MM" input field should accept exactly 2 numeric characters.</li>
<li>The "YYYY" input field should accept exactly 4 numeric characters.</li>
<li>Any attempt to enter more characters than the specified limits should be visually restricted within the input fields without allowing further input.</li>
</ul>

**Comment by vedika-gupta** [comment]
I am willing to resolve this issue, please assign it to me.

**Comment by vedika-gupta** [comment]
@theravi04 It would be great if you could give me hactoberfest label.

**Comment by theravi04** [comment]
@vedika-gupta Assigned you.

**Comment by vedika-gupta** [comment]
@theravi04 Thankyou for merging this PR.
