### ISSUE TITLE
Project : Temprature Converter

### ISSUE THREAD

**Issue by prateekpr17** [theravi04/Frontend_Projects#27]
Project Description: 🌡️ This project facilitates temperature conversions between Celsius and Fahrenheit, making it a valuable tool for everyday use.

Hi there 👋

I'm excited to contribute to Hacktoberfest 2023, and I'd like to work on this issue. It looks like a great opportunity to learn and contribute to the project.

Please assign this issue to me, and I'll start working on it right away. If you have any specific instructions or guidelines, please let me know, and I'll make sure to follow them.

Thanks a lot for considering my request!

Best regards,
Prateek Sethi

**Comment by theravi04** [comment]
@prateekpr17 Assigned you.
