### ISSUE TITLE
Adding a new project of Calculator .

### ISSUE THREAD

**Issue by RonitBaranwal** [theravi04/Frontend_Projects#30]
The websites are great but they all require a pinch of mathematic in it. So, I am thinking of adding a new project of calculator where people could calculate their day-to-day necessities.

If its okay for you , may I work on this issue and can I get it assigned.

**Comment by theravi04** [comment]
@RonitBaranwal share a screenshot of the woring project.

**Comment by RonitBaranwal** [comment]
![Screenshot 2023-10-15 150120](https://github.com/theravi04/Frontend_Projects/assets/123174522/a53d4a98-e298-42c2-aaa0-f769f7e86a6c)


The calculator will looks like this will all its functionalities working .

**Comment by theravi04** [comment]
@RonitBaranwal Assigned You.
