### ISSUE TITLE
tic - tac toe game

### ISSUE THREAD

**Issue by xshubheex** [theravi04/Frontend_Projects#37]
i want to add a tic tac toe game using  javascript.

**Comment by theravi04** [comment]
@xshubheex Assigned You.

**Comment by rituraj12797** [comment]
I CAN ALSO DO IT IN A MUCH LESSER TIM E ASSIGN IT TO ME

**Comment by theravi04** [comment]
> I CAN ALSO DO IT IN A MUCH LESSER TIM E ASSIGN IT TO ME

@rituraj12797 you can raise a new issue and get it assigned.
