### ISSUE TITLE
Add default weather locations of some important cities

### ISSUE THREAD

**Issue by kaushalkumar99** [theravi04/Frontend_Projects#6]
Would like to add default weather locations of some important cities like Delhi ,Bangalore, etc on the website page which will make the webpage look more filled up and awsome....shall i proceed ??

**Comment by theravi04** [comment]
@kaushalkumar99 how will you implement this explain....

**Comment by kaushalkumar99** [comment]
For eg:-  the city name will be taken automatically as Delhi and will not be taken from user as input and will fetch the temperature of Delhi from the same api used in the js file...
this will be placed on the left side of the page.
Similarly weather for Bangalore can be fetched and it will be placed on the right side of the page...
so people need not search for these two city's temp and can directly see on the landing page of the website....

Like in Hotel's Reception there is New York's and USA clocks too along with an Indian watch at the center

**Comment by theravi04** [comment]
@kaushalkumar99 Assigned you

**Comment by kaushalkumar99** [comment]
Ok thanks...working on it @theravi04
